[package]
name = "httm"
version = "0.10.3"
edition = "2021"

[dependencies]
clap = { version = "3.1", features = ["cargo"]}
chrono = "0.4.19"
number_prefix = "0.4.0"
fxhash = "0.2.1"
skim = "0.9.4"
lscolors = "0.9.0"
terminal_size = "0.1.17"
which = "4.2.4"
rayon = "1.5.1"
itertools = "0.10.3"