[package]
name = "httm"
version = "0.11.2"
edition = "2021"
keywords = ["zfs", "backup", "restore", "cli-utility", "snapshot"]
description = "The dream of a CLI Time Machine is still alive with httm."
repository = "https://github.com/kimono-koans/httm"
readme = "README.md"
categories = [ "command-line-utilities",  "os" ]
license = "MPL-2.0"
documentation = "https://github.com/kimono-koans/httm/blob/master/README.md"

[package.metadata.deb]
maintainer = "kimono koans <https://github.com/kimono-koans/>"
copyright = "2022, Robert Swinford <robert.swinford<...at...>gmail.com>"
license-file = ["LICENSE", "4"]
extended-description = """\
httm prints the size, date and corresponding locations of available unique versions \
(deduplicated by modify time and size) of files residing on ZFS/btrfs snapshots, but can also \
be used interactively to select and restore such files."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/httm", "usr/bin/", "755"],
    ["httm.1", "usr/share/man/man1/", "644"],
    ["README.md", "usr/share/doc/httm/README", "644"],
]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
clap = { version = "3.1", features = ["cargo"]}
chrono = "0.4.19"
number_prefix = "0.4.0"
fxhash = "0.2.1"
skim = "0.9.4"
lscolors = "0.10.0"
terminal_size = "0.1.17"
which = "4.2.4"
rayon = "1.5.1"
itertools = "0.10.3"
indicatif = "0.16.2"
lazy_static = "1.4.0"
proc-mounts = "0.3.0"