[package]
name = "httm"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "httm"
path = "src/httm.rs"

[dependencies]
clap = "3.1.5"
chrono = "0.4.19"
number_prefix = "0.4.0"
fxhash = "0.2.1"
skim = "0.9.4"
lscolors = "0.9.0"
walkdir = "2.3.2"