[package]
name = "httm"
version = "0.12.9"
edition = "2021"
keywords = ["zfs", "backup", "restore", "cli-utility", "snapshot"]
description = "A CLI tool for viewing snapshot file versions on ZFS and btrfs datasets"
repository = "https://github.com/kimono-koans/httm"
readme = "README.md"
categories = [ "command-line-utilities",  "os" ]
license = "MPL-2.0"
documentation = "https://github.com/kimono-koans/httm/blob/master/README.md"

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
strip = true
opt-level = "z"  # Optimize for size.
lto = true

[dependencies]
clap = { version = "3.2.8", features = ["cargo"] }
chrono = "0.4.19"
number_prefix = "0.4.0"
skim = "0.9.4"
lscolors = "0.10.0"
terminal_size = "0.2.0"
which = "4.2.4"
rayon = "1.5.1"
itertools = "0.10.3"
indicatif = "0.16.2"
lazy_static = "1.4.0"
proc-mounts = "0.3.0"
ahash = { version = "0.7.6", default-features = false }

[package.metadata.deb]
maintainer = "kimono koans <https://github.com/kimono-koans/>"
copyright = "2022, Robert Swinford <robert.swinford<...at...>gmail.com>"
extended-description = """\
httm prints the size, date and corresponding locations of available unique versions of files
residing on snapshots.  May also be used interactively to select and restore from such
versions, and even to snapshot datasets which contain certain files.
"""
license-file = ["LICENSE", "4"]
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/httm", "usr/bin/", "755"],
    ["httm.1", "usr/share/man/man1/", "644"],
    ["README.md", "usr/share/doc/httm/README", "644"],
]