name: Build Debian packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # push:
  #   paths:
  #     - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Build package
      run: cargo deb
    - uses: actions/upload-artifact@v3
        with:
          name: cargo-deb-upload
          path: target/debian/httm_*_amd64.deb
